feat: 슬랙으로 알림을 전송한다.
woowacourse-teams/2022-thankoo pull request #244
Opened 2022-08-09 16:33 UTC by yhh1056

## 상세 내용
- 아직 구현이 완료되지 않은 상태입니다.
- 현재 `SlackAlarmService` 의 `sendMessage()` 메서드를 사용해서 알림을 전송할 수 있어요,
- 유저의 email과 메시지를 가지고 전송하면 되는데
- 문제는 쿠폰을 받는사람, 예약을 요청받는 사람, 승인 받은 사람, 미팅날 -> 알림을 받는 사람을 조회해야해요.
- 그래서 email을 받지 않고 memberId를 받아서 `SlackAlarmService` 에서 회원을 조회하는 방식도 고민이 되네요.
- 모든 서비스에 의존을 추가하고 코드들이 반복되는데 이를 어떻게 해결하면 좋을까 고민중이에요.
- 구조적인 고민이 많이 되는데 각각의 서비스들이 `SlackAlarmService` 에 의존하게 되어 테스트도 깨질거고 인터페이스로 만들어 Fake로 테스트코드를 풀어나가야 할지고민이되네요.

설계 너무 어렵습니다😭

Close #243

2022-08-10 00:36 UTC, jayjaehunchoi requested changes
호호 코드짜느라 고생많으셨습니다!!
리뷰 몇가지 남겨두었으니 참고 부탁드려요!

또, 이벤트 리스너를 쓸 계획이라면 다른 클래스들에도 이벤트를 도입해봅시다~
그리고 이벤트 발행시 고려해야 할 사항들에 대해서도 함께 이야기 나눠봐요

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/dto/SlackUserResponse.java
> +
개행 제거

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackAlarmService.java
> +    private final CachedSlackUserRepository cachedSlackUserRepository;
사용자 입장에서 캐싱인지 DB인지 인메모리인지 알 필요가 있을까요? 저는 방식은 중요하지 않다고 생각합니당

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackAlarmService.java
> +    private final SlackMessageSender slackMessageSender;
위 리뷰와 동일합니다. Slack에 보내는지는 중요하지 않은것 같아요. 어떤 방식으로든 원하는 대상에게 원하는 메시지만 보내면 되는거라고 생각합니다.

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/cache/CachedSlackUserRepository.java
> +    @Cacheable(cacheNames = "slack", key = "#email")
1. 캐시에 존재하지 않는 경우
 - 아래 메서드를 실행하고 `email`이라는 키로 `CachedSlackUser`객체를 slack이라는 이름의 캐시에 저장한다.

2. 캐시에 존재하는 경우
- 메서드를 실행하지 않고 `CachedSlakcUser`를 가져온다.

라고 이해했습니 맞나요?

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/cache/CachedSlackUser.java
> +public class CachedSlackUser {
캐시인지 아닌지는 중요하지 않은 것 같아요.

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackClient.java
> +    private boolean equalsEmail(final String email, final SlackUserResponse userResponse) {
Email이 동일한지에 대한 비교는 `Email`이라는 VO에서 가져갈 수 있을 것 같은데 어때?

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackAlarmService.java
> +    }
알람을 동기로 전송하면 어떤 문제가 발생할까요? 또, 비동기로 보낸다면 어떤 이슈가 생길지도 함께 고민해보고 이야기나눠봐용.

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackMessageSender.java
> +                new SlackMessageRequest(channel, message.getValue()), headers);
어떤 대상에게, 어떤 메시지를 보내느냐가 중요할 것 같아요. 여러 알람 시스템을 사용하게 된다면 동일한 request로 재사용할 수 있을것 같아요. 보통 구독하고 있는 채널과 메시지로 알람을 보내게 되니까요

2022-08-10 00:36 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/config/CacheConfig.java
> +public class CacheConfig {
분리 good!

2022-08-10 01:19 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/SlackClient.java
> +    private boolean equalsEmail(final String email, final SlackUserResponse userResponse) {
생각 못 한 부분인데 변경해야겠다 👍👍👍

2022-08-10 01:19 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/alarm/cache/CachedSlackUserRepository.java
> +    @Cacheable(cacheNames = "slack", key = "#email")
제가 먼저 설명남겨두면 좋았을 부분이었네요

후니가 이해한게 맞아요!

2022-08-11 06:47 UTC, jayjaehunchoi reviewed
수고하셨습니다.

2022-08-11 06:47 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmAspect.java
> +@Profile("prod")
중요도 순으로 위치를 변경해주시죠

2022-08-11 06:47 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmAspect.java
> +        }
슬랙과 여러번 통신하는게 좀 그렇네요 한 번에 하는 방법은 없던가요?

2022-08-11 06:47 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/dto/AlarmMessageRequest.java
> +    }
부생성자는 주생성자를 이용하도록 변경해주세여

2022-08-11 06:47 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackClient.java
> +    private static final String USERS_URL = "https://slack.com/api/users.list";
property에 놔주세용

2022-08-11 06:47 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/config/AsyncConfig.java
> +        threadPoolTaskExecutor.initialize();
스레드 옵션을 다음과 같이 지정한 이유를 공유해주세여

2022-08-11 08:20 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +    }
만약 resource가 비워지지 않았다면?
비워지지 않을 경우 aop가 종료될 때 비워야 하지 않을꺄여?

2022-08-11 08:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmAspect.java
> +    public void sendMessage() {
알람이 정상적으로 보내졌다면 resource를 비워줘야 하지 않을까여?

2022-08-11 10:47 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmAspect.java
> +        }
없어요ㅜ 

외부 API 호출이 많아지는게 문제된다면 쿠폰 최대 전송수를 줄이는것도 방법이겠네요,.

2022-08-11 10:51 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/dto/AlarmMessageRequest.java
> +    }
좋은 지적입니다. 기다리고있었어요.

2022-08-11 10:51 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackClient.java
> +    private static final String USERS_URL = "https://slack.com/api/users.list";
옙

2022-08-11 10:52 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/config/AsyncConfig.java
> +        threadPoolTaskExecutor.initialize();
같이 국룰이라하면서 후니가 적은게 기억나네요 하하하

이부분 공유할게요~

2022-08-11 10:55 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +    }
하나만 알려주고 둘은 알려주지않는 후니에게 감사를 표합니다.

2022-08-11 10:55 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmAspect.java
> +    public void sendMessage() {
2222

2022-08-12 00:40 UTC, jayjaehunchoi requested changes
수정할게 조금 보이네용 수정 부탁드립니당

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/config/CacheConfig.java
> +public class CacheConfig {
불필요한 설정 파일을 삭제해주세요.

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-cache'
불필요한 디펜던시를 삭제해주세요.

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/domain/InMemorySlackUserRepository.java
> +    }
concurrentHashMap은 key, value에 null을 허용하지 않습니다. nullpointerexception을 방지할 만한 방법을 찾아보아요

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
> +    public void send(final String email, final AlarmMessage alarmMessage) {
이 친구는 어떤 트랜잭션을 탈까요?

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
> +    public void send(final String email, final AlarmMessage alarmMessage) {
걍 궁금증입니다. 만약 트랜잭션을 안탄다면 트랜잭션을 선언해줘야하지 않을까요? (하나의 작업단위라고 생각함)

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +        resources.remove();
set과는 다른 역할을 하고 있네요? 하고자 하는 행동과 다른 행동을 하는 메서드는 사이드 이펙트를 발생시킵니다.

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +    public static void setResources(AlarmMessageRequest alarmMessageEvent) {
final

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +    }
스프링에선 remove를 쓰던가요? clear라는 메서드 명도 괜찮아보이네여

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmSender.java
> +    void send(final String email, final AlarmMessage alarmMessage);
인터페이스에 final이 있네요?

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
> +    }
하나의 트랜잭션 단위가 아닐까요? 서비스 코드에 넣고 스케쥴러가 서비스 코드를 호출하는 게 더 좋아보이는데 어떠세요?? 그리고 remove를 여기서 해버리면 알람이 잘 갈까요? Alarm의 실행 시점은 after이던데요

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
> +    }
meetings라는 일급 컬렉션을 만들어 이 책임을 해당 도메인으로 이동시킬 수도 있을 것 같아요.

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
> +    }
위에서도 계속 사용하고 있네요

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
> +    private List<String> getEmails(final List<Member> members) {
members 라는 일급컬렉션을 만들어도 괜찮을것 같아요

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/meeting/domain/MeetingRepository.java
>  }
where 조건이 없네요

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
> +    }
서비스 코드에 이 메서드는 어색하지 않나요?

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
> +
개행이 추가됐네요. 제거해주세욥

2022-08-12 00:40 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java
> +    void findAllByTimeUnitDate() {
이런 테스트를 하는 경우에는 날짜가 다른 경우의 데이터도 넣어서 테스트하는게 좋을 것 같아요. 그랬다면 프로덕션 코드가 잘못되었던 것을 더 빨리 알아챌 수 있을 것 같아요

2022-08-12 00:44 UTC, sure-why-not reviewed
1차리뷰 먼저 드립니당

2022-08-12 00:44 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
> +        sendMessage(memberRepository.findByIdIn(couponRequest.getReceiverIds()));
saveaAll로 저장된 쿠폰에서 senderId 뽑아오는건 어떤가요?

2022-08-12 00:44 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +            throw new RuntimeException(ErrorType.NOT_FOUND_ALARM_REQUEST.getMessage());
커스텀 익셉션을 만들지 않은 이유가 있나요?!

2022-08-12 00:44 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmMessage.java
> +    CANCEL_RESERVATION("예약이 거절되었습니다. 확인해보러 갈까요? https://thankoo.co.kr/"),
거절되었어요. 로 말투 맞추면 좋을 것 같아요!

2022-08-12 01:48 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/config/CacheConfig.java
> +public class CacheConfig {
예리하십니다.

2022-08-12 01:49 UTC, yhh1056 commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-cache'
넵

2022-08-12 02:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +    }
clear가 더 적절해보이네요 👍

2022-08-12 02:34 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmSender.java
> +    void send(final String email, final AlarmMessage alarmMessage);
후니가 넣었나요?

2022-08-12 04:29 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmSender.java
> +    void send(final String email, final AlarmMessage alarmMessage);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ㅋㅋㅋㅋㅋㅋㅋ

2022-08-12 04:37 UTC, skullkim approved these changes

2022-08-12 05:35 UTC, jayjaehunchoi approved these changes

2022-08-12 06:22 UTC, merged

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/AlarmMessage.java
> +    CANCEL_RESERVATION("예약이 거절되었습니다. 확인해보러 갈까요? https://thankoo.co.kr/"),
임시 상수로 만든 클래스이고 각 상황별 알림을 보내려고합니다~!

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
> +    public void send(final String email, final AlarmMessage alarmMessage) {
아직 디비에 저장되는 상황이 아닌데 트랜잭션은 하나의 작업단위라는 걸 명시하기 위해 사용하자는 의견일까요?

우선 알림 전송부분을 완성하고나서 디비에 저장하는 부분을 개선해볼게요! 좋은 의견 감사해요

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/support/AlarmManager.java
> +            throw new RuntimeException(ErrorType.NOT_FOUND_ALARM_REQUEST.getMessage());
좋은 질문이네요.

아직 해당에러를 어떻게 잡아야할지 고민입니다. 다음 피알때 고민사항으로 추가할게여.

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/config/AsyncConfig.java
> +        threadPoolTaskExecutor.initialize();
저번 브라운의 의견처럼 지금 상황에서 판단할 수 있는 부분이 아니네요!!

실제 사용자들을 통해 경험하고 땡쿠만의 기준을 만들어보죠

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    NOT_FOUND_SLACK_USER(9001, "알람이 불가능한 이메일입니다. 관리자에게 문의주세요."),
좋은 의견같아!!
나도 아직 알림이 불가능한 상태에 대해 어떻게 에러를 처리해야할지 고민인데 다음 PR때 고민사항으로 추가할게!

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
> +    }
meeting, coupon, member 이 기회에 일급컬렉션으로 숨기는 방향으로 변경하려합니다.

2022-08-13 07:44 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingRepositoryTest.java
> +    void findAllByTimeUnitDate() {
좋은 의견이네요.

관련 테스트코드를 수정할게요!