refactor: 알람 관련 기능을 리팩터링한다.
woowacourse-teams/2022-thankoo pull request #270
Opened 2022-08-13 09:50 UTC by yhh1056

## 상세 내용
- Member, Coupon, Meeting 관련 일급컬렉션을 생성하여 각 필드를 조회하는 기능을 추가했습니다.
- 스케쥴에서 비즈니스로직을 수행하고 있었는데 이 로직들을 어플리케이션 레이어로 이동시켰습니다.
- 슬랙 userId를 캐싱해두는 InMemorySlackUserRepository에 대한 테스트 케이스를 추가했습니다.
  -  null이 반환되지 못 하도록 수정했는데 이 부분 다른 로직으로 해결할 수 있는지 봐주시면 감사해요.

### 알람 예외관련하여 같이 고민해주세요.
사용자의 이메일이 슬랙으로 조회할 수 없는 경우 예외가 발생합니다.
저는 이 부분은 슬랙알림이나 바로 보기 쉬운 로그로 남겨놔야 직접 이메일을 수정해주거나 크루들에게 빠른 피드백이 가능하다고 생각하여
RuntimeException으로 두고 자연스럽게 500에러로 보내게 하여 슬랙 알림이 가도록 생각했는데요.
생각해보니 해당 예외는 이미 백엔드에서 인지하고 있으므로 400대 에러라고 판단이 되었고 이에 관련하여 로그를 어떻게 남길지 같이 고민해보면 좋을 것 가탕요.

Close #268

2022-08-13 09:53 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepository.java
> +        return userToken;
슬랙에서 토큰을 조회할 때 이메일이 올바르지 않을 경우 slackClient 안에서 예외가 터지는데

여기서도 null에 대한 검증이 필요하다는 거에 대해 어떻게 생각하시나요?

2022-08-13 09:53 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUserResponse.java
> +        this.userToken = userToken;
id, userId, userToken등 계속 다른 네이밍의 변수로 사용되어서 userToken이라는 네이밍으로 통일하여

혼란이 가지않도록 수정했어요

2022-08-14 18:41 UTC, sure-why-not reviewed
호호 수고하셨어요 👍🏻👍🏻👍🏻
리뷰 남겼으니 확인해주신다면? 땡쿠 👊

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepository.java
> +@Slf4j
이건 왜 붙은건가요??

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepository.java
> +        return userToken;
null 이 들어올 일이 없는거 아닌가요??!

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
> +        @DisplayName("쿠폰이 저장되면 알람을 전송한다.")
센스 👍🏻

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
> +
공백쓰~

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
> +        meetingService.sendMessageTodayMeetingMembers(LocalDate.now());
👍🏻👍🏻 책임 분리가 좀 더 명확해 졌네요!!

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/common/schedule/MeetingScheduleTask.java
>      @Transactional
meetingService의 complete() 가 아닌 여기에 @Transactional 을 붙여준 이유가 있을까요??

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    NOT_FOUND_SLACK_USER(7001, "알람이 불가능한 이메일입니다. 관리자에게 문의주세요."),
사용자에게까지 전달되는 에러 메세지일까요??

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUserResponse.java
> +        this.userToken = userToken;
👍🏻

2022-08-14 18:41 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/meeting/application/MeetingServiceTest.java
> +                .hasMessage("전송하려는 알람이 존재하지 않습니다.")
아래랑 순서가 바뀐 것 같아요!

2022-08-14 23:15 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/dto/SlackUserResponse.java
> +        this.userToken = userToken;
좋아요~!

2022-08-14 23:17 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepository.java
> +        return userToken;
Optional과 null체크 둘 중 하나 선택하면 될 것 같아요~ 지금 수정한대로 유지해도 문제 없어보입니다~!

2022-08-14 23:30 UTC, jayjaehunchoi requested changes
호호 수고하셨습니다!! 고생 많았겠군요... 허허;;

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/alarm/infrastructure/SlackAlarmSender.java
> +            String slackUserId = slackUserRepository.findUserToken(email);
`slackUserId` -> `slackUserToken` 으로 변경해도 되겠네용

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    NOT_FOUND_SLACK_USER(7001, "알람이 불가능한 이메일입니다. 관리자에게 문의주세요."),
수정돼야할 것 같아요!

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupons.java
> +public class Coupons {
일급 컬렉션 good!

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java
> +public class Meetings {
일급 컬렉션 굳!

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java
> +    private final List<Meeting> meetings;
values라는 네이밍도 괜찮을거같네요.

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/meeting/domain/Meetings.java
> +                .map(meeting -> meeting.getMeetingMembers().getMeetingMembers())
이제봤는데 meetingMeembers.meetingMembers 이거 사건사고네요 제가 리팩터링할게용

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/member/domain/Members.java
> +    private final List<Member> members;
values는 어떠신지요 항상 일급컬렉션의 네이밍은 헷갈리네요

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/member/domain/Members.java
> +        this.members = List.copyOf(members);
결국 방어적 복사를 한 이유가 뭐였을까요??

일급 컬렉션이 updates나 delete를 할 수 없게 만든걸까요?

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/alarm/infrastructure/InMemorySlackUserRepositoryTest.java
> +
동일한 코드가 반복되네요! 분리할 수 있는 방법이 있을것 같아요

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponsTest.java
> +        Coupons result = new Coupons(coupons);
동일한 코드의 반복이 있네용

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/meeting/domain/MeetingsTest.java
> +        Meetings result = new Meetings(meetings);
동일한 코드 반복

2022-08-14 23:30 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/reservation/application/ReservationServiceTest.java
> +
네스티드 센스 굿!

2022-08-15 05:10 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/alarm/infrastructure/SlackUserFixture.java
> +    public static final String[] SKRR = {SKRR_EMAIL, SKRR_USER_TOKEN};
더 좋은 방법 where....

2022-08-15 05:23 UTC, skullkim approved these changes

2022-08-15 05:54 UTC, merged