feat: 회원/쿠폰 관련 Admin 용 조회 기능
woowacourse-teams/2022-thankoo pull request #375
Opened 2022-09-11 18:08 UTC by sure-why-not

## 상세 내용
### 구현 기능
- 이슈 확인

### 추가사항
- 네이밍
  - 프로덕트와 이름이 동일하면 혼란을 줄까봐 일단 앞에 Admin을 모두 붙였는데 추천 받습니다. ㅎ
- 어드민도 하나의 작은 서비스라고 생각하고 프로덕트의 엔티티만 사용하고 구현해봤슴니다.
- `admin` 패키지를 `thankoo` 패키지와 동일 레벨에 두고 멀티모듈 적용하면 좋을 것 같아용. 재밌을 것 같아용.
- 관리자 계정 인증 로직 필요할 것 같네용?
- `쿠폰 삭제` 기능을 개발했는데, 쿠폰 삭제하려면 미팅 삭제 -> 예약 삭제 -> 쿠폰 삭제를 진행해야 해서 호호가 먼저 머지되고 맞추는게 좋을 것 같아 현재 구현까지만 PR 날립니당
- 포함되지 않았지만 쿠폰 삭제까지 구현한 상태에서 패키지 구조는 아래와 같습니다. (호호랑 맞춰봐야징)
<img width="327" alt="스크린샷 2022-09-12 오전 3 05 21" src="https://user-images.githubusercontent.com/94965944/189542439-ca5a82e1-190b-4eb2-9d7e-7a7c59e4b93b.png">

Close #374

2022-09-11 18:13 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponController.java
> +    public ResponseEntity<List<AdminCouponResponse>> getCoupons(@RequestParam final String status) {
- 모든 쿠폰 조회 : GET /admin/coupons
- 상태별 쿠폰 조회 : GET /admin/coupons?status={status}

이렇게 하려다 method+path 중복이라 불가능해서 모든 쿠폰 조회는 status=all 로 받도록 했습니당

2022-09-12 04:06 UTC, jayjaehunchoi approved these changes
라라 꼼꼼하게 코드 잘 짜주었군요 😀

저도 멀티모듈 분리 좋습니다~! 이 부분도 코드를 다 작성한 뒤에 이야기 나눠 보아용 제가 리뷰 남긴 부분은 참고로 사용해주세용 코드 잘 짜준 것 같아서 approve 하겠습니다.

2022-09-12 04:06 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCouponStatus.java
> +}
편리한 기능이 생겼네요 ㅎㅎ

2022-09-12 04:06 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponController.java
> +    public ResponseEntity<List<AdminCouponResponse>> getCoupons(@RequestParam final String status) {
good good!!!

2022-09-12 06:03 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCouponStatus.java
> +}
ALL 때문에 프로덕션 CouponStatus를 사용하지 못하고 새로 만들었다는 슬픈 이야기...ㅜ

2022-09-12 06:06 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponService.java
> +
어떤 문제점이 발생하는지까지 알려주시다니 감사합니다👍🏻
페이징 적용하는 것 동의합니다~
프론트와도 이야기해보고 페이징 부분까지 해당 PR에 포함시킬게요!

2022-09-12 06:10 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponService.java
> +    private List<AdminCouponResponse> getCouponsByStatus(final String status) {
기간 필터 조회도 추가되는 것이 맞습니다!
혹시 조건이 더 생길 때 동적 쿼리를 사용해야하는 이유가 무엇일까요??

2022-09-12 07:50 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponService.java
> +    private List<AdminCouponResponse> getCouponsByStatus(final String status) {
필터의 경우가 세개 생기겠네요

1. 쿠폰 상태만
2. 기간만
3. 쿠폰 상태와 기간 모두

세개를 아우를 수 있는 방법은 동적 쿼리 작성이지 않을까 싶습니다!!

2022-09-16 05:52 UTC, jayjaehunchoi requested changes
1차 리뷰입니다. 더  상세히 보고 리뷰 더 남길게용

2022-09-16 05:52 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +                .andExpect(status().isOk());
parameter가 여러개니까 parameter를 넣어줄 수 있는 메서드를 고려해봐도 좋을 것 같아용

2022-09-16 05:54 UTC, yhh1056 reviewed
라라 갱장히 깔끔하게 구현해주셔서 리뷰하는데 큰 어려움이 없었습니다

빠진 테스트 케이스가 있어서 그 부분만 추가해주면 좋을 것 같아요!!

깃 꼬여서 고생많이 했을텐데 수고하셨어용

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/search/domain/AdminDateSearchCondition.java
> +        return new AdminDateSearchCondition(startDate.atStartOfDay(), endDate.atTime(LocalTime.MAX));
오우 👍👍👍

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/search/domain/AdminDateSearchCondition.java
> +
LocalDate를 받아서 날짜 검색해도 될 거같은데 Time으로 받은 이유가 있을까요? 제가 생각하지 못 한 이슈가 있을까봐유!

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/admin/member/application/AdminMemberServiceTest.java
> +        Member member = adminMemberRepository.save(new Member(LALA_NAME, LALA_EMAIL, LALA_SOCIAL_ID, SKRR_IMAGE_URL));
회원을 찾지 못 하는 경우에 대한 케이스가 빠졌어용!!

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCouponRepository.java
> +    @Modifying(clearAutomatically = true)
clearAutomatically 👍

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +                .andExpect(status().isOk());
다음처럼 객체로 사용할 수 있어요!!

.param("status", "all")
.param("startDate", "2022-01-01")

위 같이도 될거에요
```suggestion
        MultiValueMap<String, String> requestParam = new LinkedMultiValueMap<>();
        requestParam.set("status", "all");
        requestParam.set("startDate", "2022-01-01");
        requestParam.set("endDate", "2022-12-01");

        mockMvc.perform(get("/admin/coupons")
                        .params(requestParam))
                .andDo(print())
                .andExpect(status().isOk());
```

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +    void getCoupons() throws Exception {
@Nested 를 사용해서 조회에 대한 케이스를 합치는 것도 좋을 듯 해용!

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponQueryServiceTest.java
> +        Member sender = adminMemberRepository.save(new Member(LALA_NAME, LALA_EMAIL, LALA_SOCIAL_ID, SKRR_IMAGE_URL));
요기도 @Nested를 적용하는게 어떨까요?

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponQueryService.java
> +                                                                         final AdminDateSearchCondition dateSearchCondition) {
구구: 메서드명 get으로 도배할거에요?

2022-09-16 05:54 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponService.java
> +    }
이 케이스에 대한 테스트를 작성해볼까요?

2022-09-19 15:44 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/member/presentation/AdminMemberControllerTest.java
> +                Preprocessors.preprocessResponse(prettyPrint()),
추가했어용~

2022-09-19 15:44 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCouponQueryRepository.java
> +                + "AND c.created_at BETWEEN :startDateTime AND :endDateTime "
오호 감사함니다

2022-09-19 15:44 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +                .andExpect(status().isOk());
넣어브렀니다!!

2022-09-19 15:45 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/domain/AdminCoupon.java
> +public class AdminCoupon {
했슴니다~

2022-09-19 15:45 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponQueryService.java
> +    }
분기문 없애고 싶었는데 좋은 아이디어네요!
ALL 일 경우 `{"NOT_USED", "RESERVING", "RESERVED", "USED", "EXPIRED"}` 를 가져오도록 해서 하나의 쿼리로 수행하도록 변경했습니다~

2022-09-19 15:46 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/search/domain/AdminDateSearchCondition.java
> +package com.woowacourse.thankoo.admin.common.search.domain;
그렇네융...

2022-09-19 15:47 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/search/domain/AdminDateSearchCondition.java
> +
Spring Data JPA 를 사용해서 메서드로 조회하기 위함이었어요!
```java
List<Member> findAllByCreatedAtBetween(LocalDateTime startDateTime, LocalDateTime endDateTime);
```

2022-09-19 15:47 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/member/application/AdminMemberServiceTest.java
> +        Member member = adminMemberRepository.save(new Member(LALA_NAME, LALA_EMAIL, LALA_SOCIAL_ID, SKRR_IMAGE_URL));
추가했어용👍🏻

2022-09-19 15:47 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +                .andExpect(status().isOk());
👍🏻

2022-09-19 15:48 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/presentation/AdminCouponControllerTest.java
> +    void getCoupons() throws Exception {
추가했어용👍🏻

2022-09-19 15:48 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponQueryServiceTest.java
> +        Member sender = adminMemberRepository.save(new Member(LALA_NAME, LALA_EMAIL, LALA_SOCIAL_ID, SKRR_IMAGE_URL));
적용했어용~!

2022-09-19 15:48 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponService.java
> +    }
추가했어용👍🏻

2022-09-19 15:48 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/coupon/application/AdminCouponQueryService.java
> +                                                                         final AdminDateSearchCondition dateSearchCondition) {
호호는 어떤 네이밍이 적절하다고 생각하시나요??

2022-09-20 03:32 UTC, jayjaehunchoi approved these changes

2022-09-20 03:32 UTC, merged