feat: 시리얼 코드를 통한 쿠폰 발급
woowacourse-teams/2022-thankoo pull request #394
Opened 2022-09-14 13:29 UTC by yhh1056

## 상세 내용
- 이슈에 해당 기능과 고민 내용을 적어두었습니다.

- 코치가 만든 쿠폰 내용을 생성하기 위해 CoachCouponContent를 생성했는데 이 부분에 대한 필요성에 대해 같이 고민해주세요!
- CouponType에 한글 값을 추가하는 방식도 고민하다가 CoachCouponContent 클래스를 생성했어요.

Close #384

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/docs/asciidoc/coupon.adoc
> +
시리얼 관련은 admin에 있는데 라라 코드가 머지되면 추가할게요~

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/qrcode/infrastructure/QrCodeClient.java
> +                "http://api.qrserver.com/v1/create-qr-code/?data=https://thankoo.co.kr/code=" + serial + "&size=300x300",
이 부분을 프로퍼티에 빼도 될거같은데 아직 분리하지 않았어요.

큐알을 찍었을 때 이동할 url을 프론트와 내일 고민해볼게요

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/presentation/AdminCouponSerialController.java
> +@RequestMapping("/admin/serial")
coupon-serial?

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    NOT_FOUND_COUPON_SERIAL(8001, "존재하지 않는 시리얼 번호입니다."),
쿠폰 시리얼

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CoachCouponContent.java
> +    private static final String TITLE = "{0}가(이) 보내는 {1} 쿠폰";
공백 추가

2022-09-14 13:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CoachCouponContent.java
> +        MEAL(CouponType.MEAL, "식사");
한글값을 CouponType에 준다면 CoachCouponContent 클래스는 없어져도 될듯해요

2022-09-14 14:26 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
> +    }
쿠폰시리얼멤버 객체에서 쿠폰을 생성하는 메서드로 옮길게용

2022-09-15 05:21 UTC, jayjaehunchoi requested changes
호호 수고하셨어요!! 꽤나 해야할 일이 많겠네요 화이팅!

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
> +                                                           @RequestBody final CouponSerialRequest request) {
다른 데에서는 full name을 적고 있네요

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/CouponSerialRequest.java
> +    private String coachName;
name을 받아오네요? id를 받는 것은 어떤가요?

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/CouponSerialRequest.java
> +    private String coachName;
저희 name은 unique 가 아니에요

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialService.java
> +    }
serial code가 중복된다면 어떻게 되나요?

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerial.java
> +
code 제약조건 없나요?

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialMember.java
> +    public Long getId() {
Lombok 쓰시죠

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
> +    @PostMapping
/api/coupons -> /api/coupons/serial 이런 형태로 써도 괜찮을 것 같고 지금 유지해도 좋을 것 같아욥

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/admin/common/qrcode/presentation/QrCodeControllerTest.java
> +class QrCodeControllerTest extends ControllerTest {
상속 받을 필요 있나요? admin의 컨트롤러 테스트네용

2022-09-15 05:21 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/admin/serial/presentation/CouponSerialControllerTest.java
> +class CouponSerialControllerTest extends ControllerTest {
앞선 테스트와는 다른 컨텍스트를 띄울거같아요. 차라리 어드민을 한 데 묶는 건 어때요?

2022-09-15 06:34 UTC, skullkim approved these changes

2022-09-17 03:08 UTC, jayjaehunchoi commented
이미 사용한 시리얼 넘버에 대한 검증이 있나요? 

지난 번에 고민하던 내용을 시리얼 넘버 사용 -> 이벤트 -> 쿠폰 생성의 과정으로 이어진다면 의존관계도 분리할 수 있고 사용된 시리얼 넘버에 대한 검증도 적절한 지점에 추가할 수 있겠네용

2022-09-18 12:33 UTC, yhh1056 reviewed
![스크린샷 2022-09-18 오후 9 33 22](https://user-images.githubusercontent.com/58363663/190902277-a97279f6-e8ff-4874-a8b1-2912eb722da7.png)

이번엔 테스트 더 꼼꼼하게 작성했습니당

2022-09-18 12:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponContentFactory.java
> +}
시리얼로 생성되는 쿠폰의 경우 "누구가 누구에게 보내는 쿠폰" 같은 뷰의 값이 도메인에 있었어요.

이를 도메인과 분리하고자 `CouponContentFactory` 를 생성했고 각 구현체들은 입맛에 맞게 쿠폰 컨텐츠를 생성할 수 있도록 제공해줍니다. 

하지만 결국 구현체인 `CouponSerialContent` 객체도 도메인 레이어에 있는데요 이를 어디 계층에 넣어야 할지 판단이 되지 않더라구요.
`CouponSerialContent`객체의 설명은 따로 코멘트 남길게요.

2022-09-18 12:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialContent.java
> +public class CouponSerialContent implements CouponContentFactory {
`CouponSerialMember`를 상태로 가지게 되었어요. 
처음엔 `CouponSerialMember` 안에서 `CouponSerialContent` 객체를 생성해서 쿠폰 내용을 만들었는데 두 객체간에 
강결합이 발생해서 `CouponSerialContent`가 `CouponSerialMember` 를 단방향으로 의존하는 방식으로 설계했고
이를 어플리케이션 레이어에서 생성하도록 구현했어요.

많이 고민해보고 결정했는데 이에 대한 피드백이 필요합니다😭

2022-09-20 04:53 UTC, jayjaehunchoi approved these changes
확인바람

2022-09-20 07:52 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/util/RandomUtils.java
> +public class RandomUtils {
예 해봤네요^^ 랜덤이 1.5배정도 빠릅니다 데이터 천만건 생성해서 비교해봤어여

// 2614551212  random
// 4014452123  uuid

// 2524619212 random
// 3998764737 uuid

2022-09-20 09:55 UTC, sure-why-not requested changes
20000

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/application/CouponSerialService.java
> +    private static void validateStatus(final CouponSerialStatus status) {
static 메서드인 이유가 있나요? 
해당 검증은 couponSerial.use로 이동해야할 것 같아요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerial.java
> +public class CouponSerial extends BaseEntity {
equals  & h & toString 재정의 해주세요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/SerialCode.java
> +    private static boolean isValidCode(final String code) {
이것도 static이네용

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialService.java
> +        if (couponSerialRepository.existsBySerialCodeValue(serialCodes.getSerialCodeValues())) {
어드민에서만 사용되니 AdminCouponSerialQueryRepository 에서 처리하면 좋을 것 같아요

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialService.java
> +    private static List<CouponSerial> create(final CouponSerialRequest couponSerialRequest,
이것도 static이네용

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialService.java
> +                .orElseThrow(() -> new InvalidMemberException(ErrorType.NOT_FOUND_MEMBER));
저는 어드민용 exception이랑 errorType을 분리했어요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialService.java
> +        Member coach = getMember(couponSerialRequest.getMemberId());
coach라고 명시하지 않아도 좋을 것 같아요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/infrastructure/RandomStringCodeCreator.java
> +    private static final int END_INDEX = 122;
숫자끼리 묶으면 좋을 것 같아요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/infrastructure/RandomStringCodeCreator.java
> +                .filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97))
어떤 조건문인지 분리해주세요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/serial/presentation/AdminCouponSerialController.java
> +    public ResponseEntity<List<CouponSerialResponse>> getSerial(@RequestParam("memberId") final Long memberId) {
```suggestion
    public ResponseEntity<List<CouponSerialResponse>> getSerials(@RequestParam("memberId") final Long memberId) {
```

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/qrcode/presentation/QrCodeController.java
> +package com.woowacourse.thankoo.admin.common.qrcode.presentation;
common 패키지에 있네요! 밖으로 빼도 좋을 것 같아요

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialStatus.java
> +    NOT_USED, USED;
개행 넣어주세요!

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/domain/CouponSerialContent.java
> +public class CouponSerialContent {
e q & h 
tS
부탁

2022-09-20 09:55 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/serial/application/dto/CouponSerialRequest.java
> +package com.woowacourse.thankoo.serial.application.dto;
```suggestion
package com.woowacourse.thankoo.admin.serial.application.dto;
```

2022-09-21 00:51 UTC, jayjaehunchoi requested changes
build가 터지네요 확인해주세요!

2022-09-21 01:36 UTC, sure-why-not approved these changes
마지막...

2022-09-21 01:36 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/common/qrcode/presentation/QrCodeControllerTest.java
> +class QrCodeControllerTest extends AdminControllerTest {
```suggestion
@DisplayName("AdminQrCodeController 는 ")
@WebMvcTest(AdminQrCodeController.class)
class AdminQrCodeControllerTest extends AdminControllerTest {
```

2022-09-21 01:36 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/serial/application/AdminCouponSerialServiceTest.java
> +@DisplayName("CouponCouponSerialService 는 ")
```suggestion
@DisplayName("AdminCouponCouponSerialService 는 ")
```

2022-09-21 01:36 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/serial/domain/AdminRandomStringCodeCreatorTest.java
> +class AdminRandomStringCodeCreatorTest {
@DisplayName

2022-09-21 01:36 UTC, sure-why-not commented on backend/src/test/java/com/woowacourse/thankoo/admin/serial/domain/AdminSerialCodesTest.java
> +@DisplayName("CouponSerials 는 ")
```suggestion
@DisplayName("AdminCouponSerials 는 ")
```

2022-09-21 01:45 UTC, jayjaehunchoi approved these changes

2022-09-21 01:45 UTC, merged