refactor: 기본 유저 이미지 변경
woowacourse-teams/2022-thankoo pull request #401
Opened 2022-09-15 02:36 UTC by kwannee

## 상세 내용
- 기본 유저 이미지를 사용되는 곳에 맞춰 사이즈를 변경한다.
- 백그라운드를 추가하여 가시성을 개선한다.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/41886825/190300364-ff903f92-3225-4f49-b707-cf3f6b497bef.png">

<img width="437" alt="image" src="https://user-images.githubusercontent.com/41886825/190300209-1fc22610-dd5d-4f46-8e43-2ff2523f8b89.png">

Close #399

2022-09-15 11:09 UTC, kwannee commented on frontend/src/components/@shared/ProfileIcon.tsx
> +      <DefaultUserIcon size={size} />
유저 아이콘을 바로 사용하는게 아니라 감싸줬습니다. size도 줬어요

2022-09-15 11:09 UTC, kwannee commented on frontend/src/components/@shared/ProfileIcon.tsx
> +`;
헤더에 있는 작은 버튼에서 사용하는게 1.5em 정도더라고요 그래서 디폴트로 줬고, 유저프로필 페이지에서는 size를 넘겨주도록 했습니다.

2022-09-15 11:09 UTC, kwannee commented on frontend/src/types/custom.d.ts
> +declare module '*.webp';
파일 지웠는데 까먹고 안지웠네요 근데 있으면 좋죠 뭐

2022-09-15 11:09 UTC, kwannee commented on frontend/webpack/webpack.common.js
> +        test: /\.(png|jpe?g|gif|svg|ico|webp)$/i,
이하동문

2022-09-15 11:09 UTC, kwannee commented on frontend/src/pages/UserProfile.tsx
> -import defaultUser from '../assets/images/default_user.jpeg';
이거 안쓰고 있었음ㅋㅋ

2022-09-16 00:08 UTC, KangYunHo1221 approved these changes
즐거운 예비군 잘 받으세요

2022-09-16 00:08 UTC, KangYunHo1221 commented on frontend/src/components/@shared/ProfileIcon.tsx
> +      <DefaultUserIcon size={size} />
네이밍 변경 좋네요

2022-09-16 00:08 UTC, KangYunHo1221 commented on frontend/src/components/@shared/UserProfileButton.tsx
> +      <ProfileIcon src={profile ? profile?.imageUrl : 'default'} size={'28px'} />
나중에 시간이 남는다면... 대대적인 px와 rem 변환작업을 해봅시다

2022-09-16 00:08 UTC, KangYunHo1221 commented on frontend/webpack/webpack.common.js
>              loader: 'file-loader',
how about using asset, instead of 'file-loader'

2022-09-16 00:08 UTC, KangYunHo1221 requested changes
실수로 approve 해버림. asset으로 바꿔줭

2022-09-19 10:22 UTC, merged