feat: 헤더와 바텀 nav의 리렌더링을 막는다.
woowacourse-teams/2022-thankoo pull request #422
Opened 2022-09-20 07:32 UTC by kwannee

## 상세 내용
- 헤더와 바텀 Nav를 포함한 Layout 컴포넌트를 만들었다.
- 해당 컴포넌트에서는 `Outlet`을 `Suspense`로 감싸 페이지 전환 시 `헤더`와 `바텀 nav`를 제외한 컨텐츠만 리렌더링 되도록 했다.
- @shared 폴더에 Layout 폴더를 추가로 생성해 Layout과 관련한 컴포넌트들을 옮겼다.
- 그래서 파일 체인지가 많아 보이긴 하는데 실제로 추가된 코드는 많이 없다.

Close #420

2022-09-20 16:31 UTC, kwannee reviewed
나름 자세히 쓸려고 노력했습니다. 궁금한 점은 질문부탁드려요~

2022-09-20 16:31 UTC, kwannee commented on frontend/src/components/@shared/Layout/HeaderAndNavLayout.tsx
> +    </PageLayout>
PageLayout은 기본적으로 우리가 정의한거
UserProfile은 헤더가 있으면 다 있는거니까 넣었습니다
Outlet에 Suspense를 줘서 페이지 전환 시(아웃렛 변경 시) 변경 부분에만 Spinner가 돌도록 했습니다
그래서 페이지 전환 시에 리렌더링을 막았어요

2022-09-20 16:31 UTC, kwannee commented on frontend/src/components/@shared/Layout/MainPageLayout.tsx
> +`;
얘는 HeaderAndNavLayout을 사용하는 애들도 그 내부 레이아웃은 따로 정의해야 하고,
근데 또 걔네들도 공통됐기 때문에 따로 만들어줬습니다.
HeaderAndNavLayout에 그냥 이 레이아웃을 박아넣을까도 생각했는데 결합이 너무 높아지는거 같아서 하지 않았어요.
이 레이아웃을 쓰지 않으면서도 Header와 Nav를 사용하는 페이지가 만들어 질 수도 있을 것 같았습니다

2022-09-20 16:31 UTC, kwannee commented on frontend/src/components/@shared/noContent/NoMeeting.tsx
> +        </S.IconWrapper>
빈 페이지 새가 최초 렌더링 시 없다가 생기니까 reflow가 생기더라고요. 그래서 IconWrapper로 미리 공간을 잡아놨습니다

2022-09-20 16:31 UTC, kwannee commented on frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx
> +    flex: 1;
이거를 바꾼게 height가 줄어드니까 새가 overflow 하더라고요. 그래서 그냥 position이 absolute가 아니어도 되겠다 싶어서 바꿨습니다.
display:grid; place-items:center 는 flex,justify:center,align:center 한거랑 똑같습니다. 그냥 한 줄 적어서 저렇게 했어요

2022-09-20 16:31 UTC, kwannee commented on frontend/src/constants/coupon.ts
> +  meal: require('../assets/images/meal_coupon.svg'),
이거는 스꺼리에게 말해서 서버에서 받아오도록 수정할 예정입니다 일단은 이렇게 쓰시죠

2022-09-20 16:31 UTC, kwannee commented on frontend/src/pages/Main.tsx
> +            color: white;
bolder를 지운거는 폰트를 바꾸니까 bolder시 너무 bolder더라고요. 그래서 지웠습니다.
white한거는 Layout 빼니까 color가 black이 돼가지고 바꿨습니다.

2022-09-20 16:31 UTC, kwannee commented on frontend/src/pages/OnFailurePage.tsx
> +    </Suspense>
오우 이건 실수인데요
혹시나 새벽감성에 볼까 싶어서 일단 코멘트 달겠습니다. Suspense를 여기다 달면 동작이 안될 겁니다.
파일을 불러와야 서스펜스가 달리는 건데 파일 안에 서스펜스를 넣어놓으면 당연히 안되겠죠.
현재는 Router에서 Outlet 이용해서 Suspense 하고 있습니다.
내일 가서 고칠게요

2022-09-20 16:31 UTC, kwannee commented on frontend/src/pages/OnSuccessPage.tsx
> +    </Suspense>
얘도 마찬가지입니다. 지워야돼요

2022-09-20 16:31 UTC, kwannee commented on frontend/src/routes/Router.tsx
> +};
Header랑 Nav 없는 페이지에서는 모든 컴포넌트가 로딩 시 Spinner를 보여주도록 했습니다.

2022-09-20 16:31 UTC, kwannee commented on frontend/src/routes/Router.tsx
> +        </Route>
이거는 Header와 Nav가 있는 레이아웃들입니다. 서스펜스는 HeaderAndNavLayout 안에 들어있어요.

이렇게 하는 방법도 있고 다른 방법도 있을 것 같아요.
HeaderAndNavLayout 에서 서스펜스 부분은 빼고 서스펜스는 각 Route의 element에 다 따로 써주는 거죠.
```jsx
<Route element={<HeaderAndNavLayout />}>
  <Route path={ROUTE_PATH.MAIN} element={
    <Suspense fallback={<Spinner />}>
      <Main />
    </Suspense>
  } />
   ... // 이후 모든 Route 이렇게 다 바꿈
</Route>
```
which way do you prefer?

2022-09-21 04:30 UTC, KangYunHo1221 requested changes
코멘트 남겼읍니다

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/components/@shared/noContent/NoMeeting.tsx
> +        </S.IconWrapper>
``javascript
meetings.length ? <Meeting> : <NoContent>;``

깜빡인다는 
NoContent와 Meeting이 담당하는 영역이 달라서
meetings 유무에 따라서 깜빡인다는 의미인가요??

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/components/@shared/noContent/NoReceivedCoupon.tsx
> +    flex: 1;
Mixin 만들었는데 재사용 하죠 ㅋㅋㅋ

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/pages/Main.tsx
> +        )}
빼봅시다 나중에

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/pages/OnFailurePage.tsx
> +    </Suspense>
고치세요

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/pages/OnSuccessPage.tsx
> +    </Suspense>
지우세요

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/routes/Router.tsx
> +      </Route>
이쁘던데요

2022-09-21 04:30 UTC, KangYunHo1221 commented on frontend/src/routes/Router.tsx
> +        </Route>
Route에 붙어있는게 나을 것 같습니다.

2022-09-21 05:18 UTC, KangYunHo1221 approved these changes
고오맙다 스컬아

2022-09-21 05:18 UTC, merged