feat: 쿠폰을 즉시 사용한다.
woowacourse-teams/2022-thankoo pull request #496
Opened 2022-09-29 02:20 UTC by yhh1056

## 상세 내용
- 코멘트에 남겨둘게용

Close #492

2022-09-30 00:51 UTC, jayjaehunchoi requested changes
리뷰남겼습니다. 확인해주세요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    CAN_NOT_COMPLETE_MISMATCH_MEMBER(3009, "쿠폰을 즉시사용할 수 있는 회원이 아닙니다."),
코드가 같네요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +        }
두 검증이 이벤트보다 선행돼야하지않을까요?

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +        if (couponStatus.isReserved() || couponStatus.isUsed() || couponStatus.isExpired()) {
세 내용을 묶어서, 즉시사용 불가한 상태라고 명시해주면 더 좋을 것 같아요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
> +    }
테스트가 없었나보네요, 다시 확인해주세요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/CouponEventListener.java
> +public class CouponEventListener {
저는 서비스에 만드는 걸 선호하지만 이런 방식도 괜찮을 것 같아요.

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
> +        reservationStatus = ReservationStatus.ACCEPT;
complete가 ACCEPT인 이유는 뭘까요? 즉시 사용한것과 예약이 수락된 것이 같은 의미는 아닌 것 같아요.

그리고 컴플리트 할 때 검증이 없네요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
> +        void Complete() {
메서드명이 대문자로 시작하네요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
> +                    .status(HttpStatus.OK.value());
실패사례도 체크하면 컨트롤러에서 로직을 안넣었던 것을 잘 확인할 수 있었을 것 같아요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/reservation/application/CouponEventListenerTest.java
> +class CouponEventListenerTest {
eventListener 테스트가 아니라, CouponService 테스트에 있는게 적절해보이네요

2022-09-30 00:51 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponCompleteEvent.java
> +public class CouponCompleteEvent {
보통 이벤트 클래스는 과거형을 사용합니다

2022-09-30 02:08 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    CAN_NOT_COMPLETE_MISMATCH_MEMBER(3009, "쿠폰을 즉시사용할 수 있는 회원이 아닙니다."),
코드 수정했습니다

2022-09-30 02:26 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +        }
트랜잭션이 전파되기 전 예외가 발생하도록 수정하고 메서드로 추출했어요

2022-09-30 03:40 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +        if (couponStatus.isReserved() || couponStatus.isUsed() || couponStatus.isExpired()) {
해당 관련된 부분 리팩토링했습니다~

2022-09-30 05:14 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
> +    }
인수테스트에서 검증이 빠져있었네요. 테스트 추가하고 로직 추가했습니다~

2022-09-30 05:15 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/CouponEventListener.java
> +public class CouponEventListener {
컨트롤러에서 추가적인의존이 필요해서 서비스에 합치게 되었는데 분리하면 어떤 장점이 있을까요?

2022-09-30 05:17 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/reservation/application/CouponEventListenerTest.java
> +class CouponEventListenerTest {
이벤트리스너도 서비스로 옮기면서 자연스래 수정됐어요

2022-09-30 05:22 UTC, yhh1056 commented on backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
> +                    .status(HttpStatus.OK.value());
조아요

2022-09-30 05:46 UTC, sure-why-not approved these changes
호호 수고하셨어용 ㅎ

2022-09-30 05:46 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    }
```suggestion
    private void validateStatus() {
        if (!couponStatus.canChangeComplete()) {
            throw new InvalidCouponException(ErrorType.CAN_NOT_COMPLETE);
        }
```
이 부분은 CouponStatus에서 해주는건 어떨까요??

2022-09-30 05:46 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    CAN_NOT_COMPLETE(3009, "쿠폰을 즉시사용할 수 있는 상태가 아닙니다."),
```suggestion
    CAN_NOT_USE_COUPON(3009, "쿠폰을 즉시사용할 수 있는 상태가 아닙니다."),
```

2022-09-30 05:46 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    public void complete(final Long memberId) {
저는 쿠폰을 완료한다는 것보단 사용한다 `use()`가 더 적절할 것 같은데 어떤가용?

2022-09-30 10:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    }
status에게 던지도록 수정했어요!

2022-09-30 10:33 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    public void complete(final Long memberId) {
api 도 use 라는 이름으로 수정했습니다

2022-09-30 10:37 UTC, skullkim approved these changes

2022-10-01 05:12 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/CouponEventListener.java
> +public class CouponEventListener {
컨트롤러에 추가적인 의존이 필요하지 않을 것 같은데요, 어떤 경우였나요?

분리하면 장점은, 이벤트 리스너 내용이 수정이 필요하다면 이벤트 리스너만 확인하면 된다가 가능하겠네요,
다만 트랜잭션은 주로 Service에서 관리하기 때문에 또 다른 사용자들이 이벤트 리스너에 존재하는 트랜잭셔널에 의문을 품을 수도 있을 것 같아요

2022-10-01 05:23 UTC, jayjaehunchoi requested changes
확인 부탁드립니다!

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/common/exception/ErrorType.java
> +    CAN_NOT_COMPLETE_MISMATCH_MEMBER(3010, "쿠폰을 즉시사용할 수 있는 회원이 아닙니다."),
```suggestion
    CAN_NOT_USE_MISMATCH_MEMBER(3010, "쿠폰을 즉시사용할 수 있는 회원이 아닙니다."),
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/application/CouponService.java
> +    public void complete(final Long memberId, final Long couponId) {
```suggestion
    public void useImmediately(final Long memberId, final Long couponId) {
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    private boolean isExchangedMember(final Long memberId) {
교환된멤버인가? 라는 의미네요.

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    private void validateExchangedMember(final Long memberId) {
```suggestion
    private void validateMemberCanUseCoupon(final Long memberId) {
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +        if (couponStatus.isReserving()) {
```suggestion
        if (isReserving()) {
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/CouponStatus.java
> +    public boolean isCompleteStatus() {
종료된 상태인가? 라는 의미네요.
```suggestion
    public boolean isStatusAbleToComplete() {
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/presentation/CouponController.java
> +    public ResponseEntity<Void> complete(@AuthenticationPrincipal final Long memberId,
```suggestion
    public ResponseEntity<Void> useCouponImmediately(@AuthenticationPrincipal final Long memberId,
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
> +    public void complete(final CouponCompleteEvent event) {
```suggestion
    public void cancelReservation(final CouponCompleteEvent event) {
```

2022-10-01 05:23 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
> +        if (coupon.isReserving()) {
reservation waiting인지도 확인해야할 것 같네요

2022-10-01 09:43 UTC, yhh1056 commented on backend/src/main/java/com/woowacourse/thankoo/reservation/domain/Reservation.java
> +        if (coupon.isReserving()) {
해당 부분에 대한 테스트케이스 추가했습니다

2022-10-03 14:56 UTC, jayjaehunchoi requested changes

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/coupon/domain/Coupon.java
> +    private boolean isAttendee(final Long memberId) {
쿠폰의 참여자는 조금 어색해보이네용
```suggestion
    private boolean canMemberUseCoupon(final Long memberId) {
```

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/reservation/application/ReservationService.java
> +    }
이벤트 리스너는 따로 두고, 서비스에 application 로직을 두자는 의견이었는데 잘못 전달되었던 것 같아요.

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/acceptance/CouponAcceptanceTest.java
> +            Long couponId = couponResponse.getCouponId();
합칠 수 있지 않을까요?

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/coupon/application/CouponServiceTest.java
> +            Member sender = memberRepository.save(new Member(HUNI_NAME, HUNI_EMAIL, HUNI_SOCIAL_ID, SKRR_IMAGE_URL));
메서드 명이 변경되었으니, 테스트 메서드 명과 디스플레이 네임도 변경되어야 할 것 같아요

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponStatusTest.java
> +    void isNotUsed(CouponStatus status) {
스컬이가 제게 테스트 아규먼트에 final 붙이라고 리뷰남겨서 쭉 붙이고 있었는데, 생각해보니까 테스트에는 안붙이기로 했던것같네요?

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java
> +    class CompleteTest {
프로덕션에서 변경된 이름에 맞게 변경해주세요, 몇몇 변경 안 된 부분이 있어서 다른 곳들도 확인해야할것같아요

2022-10-03 14:56 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/coupon/domain/CouponTest.java
> +    class CompleteTest {
```suggestion
    class UseTest {
```

2022-10-04 10:16 UTC, jayjaehunchoi approved these changes

2022-10-04 11:37 UTC, merged