feat: 어드민 로그인 api를 구현한다
woowacourse-teams/2022-thankoo pull request #503
Opened 2022-10-01 08:31 UTC by skullkim

## 상세 내용
- 어드민 로그인 api
- 어드민 계정 인가

당장은 어드민 id를 파라미터로 받아도 할게 없어서 Resolver는 구현하지 않았어요.

Close #487

2022-10-01 12:39 UTC, skullkim commented on backend/src/docs/asciidoc/index.adoc
> +
수정할게요~

2022-10-01 12:46 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +public class Administrator extends AdminBaseEntity {
네~

2022-10-01 12:50 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/application/AdminAuthenticationService.java
> +        String encryptedPassword = passwordEncryption.encrypt(loginRequest.getPassword());
Administrator라는 도메인은 어드민에 대한 상태를 가지고 있는 것만으로도 책임을 다하고 있다고 생각했어요. 패스워드를 암호화 해야 한다는 것은 보안을 더 철저하게 하고, 법을 지키기 위한 수단이죠. 따라서 암호화 부분은 인증, 인가에 있는 것이 적절하다고 생각돼요. 따라서 패스워드를 암호화 하는 로직은 인증, 인가 부분에 존재해야 한다고 생각해요.

2022-10-01 12:53 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/presentation/AdminAuthenticationController.java
> +        AdminSignInResponse loginResponse = authenticationService.signIn(loginRequest);
합칠게요~

2022-10-01 13:00 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/presentation/AdminAuthenticationControllerTest.java
> +                getResponsePreprocessor(),
추가할게요!

2022-10-01 13:03 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/PasswordEncryptionTest.java
> +    PasswordEncryption passwordEncryption;
추가할게요

2022-10-01 13:03 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/TokenProviderTest.java
> +    TokenProvider accessTokenProvider;
추가할게요

2022-10-01 13:04 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/TokenProviderTest.java
> +        final String token = accessTokenProvider.create("payload");
삭제할게요

2022-10-01 13:08 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/exception/CannotEncryptPasswordException.java
> +public class CannotEncryptPasswordException extends AdminBadRequestException {
삭제할게요

2022-10-01 13:08 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/exception/InvalidAdminAuthenticationException.java
> +public class InvalidAdminAuthenticationException extends UnauthenticationAdminException {
삭제할게요

2022-10-01 13:10 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/presentation/AdminSignInInterceptor.java
> +        String accessToken = AuthorizationExtractor.extract(request)
아.. 변경할게요

2022-10-01 13:13 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/infrastructure/HashEncryption.java
> +public class HashEncryption implements PasswordEncryption {
변경할게요

2022-10-01 13:14 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/infrastructure/HashEncryption.java
> +    private static final String PBKDF2_WITH_SHA1 = "PBKDF2WithHmacSHA1";
네~

2022-10-01 13:19 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/infrastructure/HashEncryption.java
> +import org.apache.commons.codec.binary.Base64;
잘못추가했네요. java.util로 변경할게요

2022-10-01 13:32 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/UnauthenticationAdminException.java
> +public class UnauthenticationAdminException extends RuntimeException {
수정할게요

2022-10-01 13:34 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    private String password;
검증할게 없다고 판단돼서 안했어요. password는 해시화돼서 들어오니 특정 조건을 만족했는지 알 수없고, 이름도 검증할 부분이 없다고 판단했어요.

2022-10-02 05:05 UTC, jayjaehunchoi requested changes
리뷰 확인 부탁드립니다.

2022-10-02 05:05 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/PasswordEncryptionTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
ApplicationTest 애노테이션이 있습니다. 다른 곳에서도 SpringBootTest를 사용하는 것으로 보이는데, 수정해주세요

2022-10-02 05:05 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/common/ControllerTest.java
> +    protected TokenDecoder tokenDecoder;
여기에 추가돼야할 이유가 있나요?

2022-10-02 05:05 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    private String name;
name을 로그인 아이디라고 생각하긴 어려울 수도 있겠네요, 그런데 저희끼리만 잘 이야기하면 될 것 같아요

2022-10-02 05:05 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    public Administrator(final Long id, final String name, final String password,
관리자에는 최소한의 제약조건이 없나요?

2022-10-02 09:26 UTC, sure-why-not approved these changes
수고했스껄☠️

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +                         final AdministratorRole role) {
```suggestion
    public Administrator(final Long id, 
                        final String name,
                        final String password,
                        final AdministratorRole role) {
```

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +                         final AdministratorRole role) {
```suggestion
    public Administrator(final String name, 
                         final String password,
                         final AdministratorRole role) {
```

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/AdministratorRole.java
> +    ROOT;
```suggestion
public enum AdministratorRole {

    ROOT;
```
개행 추가해주세용~~

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    @Column(name="role", nullable = false)
```suggestion
    @Column(name = "name", length = 20, nullable = false, unique = true)
    private String name;

    @Column(name = "password", nullable = false)
    private String password;

    @Column(name = "role", nullable = false)
```
코드 포맷팅을 생활화합시다. ☠️

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/AdminErrorType.java
> +    INVALID_TOKEN("유효하지 않은 토큰입니다");
```suggestion
    CANNOT_ENCRYPT_PASSWORD("비밀번호를 암호화할 수 없습니다."),
    INVALID_LOGIN_INFORMATION("올바르지 않은 비밀번호 또는 이름입니다."),
    NOT_AUTHENTICATED("인증되지 않은 어드민입니다."),
    ALREADY_AUTHENTICATED("이미 인증된 어드민입니다."),
    INVALID_TOKEN("유효하지 않은 토큰입니다");
```
이렇겐 어떠신가용?

2022-10-02 09:26 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/UnAuthenticationAdminException.java
> +public class UnAuthenticationAdminException extends RuntimeException {
현재 admin패키지에 추가된 클래스는 모두 `Admin` 접두어가 붙어있어요! 고려해주시면 감사하겠슴니다🙏🏻

2022-10-03 14:58 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/UnAuthenticationAdminException.java
> +public class UnAuthenticationAdminException extends RuntimeException {
인스타 카페 st

2022-10-03 15:12 UTC, jayjaehunchoi requested changes
good~!

2022-10-03 15:12 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/application/dto/AdminSignInRequest.java
> +    }
request에 toString을 재정의한 이유가있나용?

2022-10-03 15:12 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/domain/TokenProvider.java
> +    String create(final String payload);
```suggestion
    String create(String payload);
```

2022-10-03 15:12 UTC, jayjaehunchoi commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/presentation/dto/AdminSignInResponse.java
> +                ", accessToken='" + accessToken + '\'' +
민감한 정보는 Masking 해주세용

2022-10-03 15:12 UTC, jayjaehunchoi commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/PasswordEncryptionTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
그리고 만약 저라면, 테스트 성능을 위해 스프링을 안띄울 것 같긴해요. 모든 게 다 스프링 없이 생성자 주입으로 가능해보여용

2022-10-03 15:52 UTC, sure-why-not commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/UnAuthenticationAdminException.java
> +public class UnAuthenticationAdminException extends RuntimeException {
정답 ㅋ

2022-10-04 06:22 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/common/exception/UnAuthenticationAdminException.java
> +public class UnAuthenticationAdminException extends RuntimeException {
수정은 DM으로 문의해주세요🙏🏻

2022-10-04 10:51 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +                         final AdministratorRole role) {
수정할게요~

2022-10-04 10:51 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +                         final AdministratorRole role) {
수정할게요~

2022-10-04 10:51 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/AdministratorRole.java
> +    ROOT;
수정할게요~

2022-10-04 10:58 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/admin/authentication/domain/PasswordEncryptionTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
스프링 없이 생성자 주입을 하는 방식으로 바꿀게요~

2022-10-04 10:58 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    private String name;
한번 같이 얘기해봐요

2022-10-04 11:01 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/administrator/domain/Administrator.java
> +    public Administrator(final Long id, final String name, final String password,
검증할 수 있는 제약조건이 떠오르지 않아서 추가하지 않았어요. 어떤 제약 조건을 추가할 수 있을까요?

2022-10-04 11:07 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/application/dto/AdminSignInRequest.java
> +    }
모든 request에 다 재정의 되있는대요?

2022-10-04 11:07 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/domain/TokenProvider.java
> +    String create(final String payload);
수정할게요~

2022-10-04 11:09 UTC, skullkim commented on backend/src/main/java/com/woowacourse/thankoo/admin/authentication/presentation/dto/AdminSignInResponse.java
> +                ", accessToken='" + accessToken + '\'' +
반영할게요

2022-10-04 11:13 UTC, skullkim commented on backend/src/test/java/com/woowacourse/thankoo/common/ControllerTest.java
> +    protected TokenDecoder tokenDecoder;
잘못 추가했다가 지우는걸 깜빡했네요. 삭제할게요~

2022-10-04 11:14 UTC, skullkim commented on backend/src/docs/asciidoc/index.adoc
> +
코딩 컨벤션을 자동 수정으로 바꾸던 중 바뀐거 같네요. 원래대로 수정할게요

2022-10-05 11:15 UTC, jayjaehunchoi approved these changes

2022-10-05 11:16 UTC, merged