chore : storybook 설치
woowacourse-teams/2022-thankoo pull request #626
Opened 2022-10-25 07:55 UTC by kwannee

## 상세 내용
- 스토리북을 설치했습니다.
- 버튼 컴포넌트에 대한 스토리를 작성했습니다.
- ListViewHeart의 콕 버튼을 해당 커스텀 버튼으로 대체했습니다.
- 버튼 컴포넌트 loading 시 내부 컨텐츠를 로딩 스피너로 대체했습니다. 그 이유는 `중..`이라는 단어가 콕과 함께 쓰니 `콕중...` 이라고 보여서 범용성이 떨어진다고 판단했습니다.
- ListViewHeart에 suspense를 달았습니다. fallback으로는 ListViewHeartSkeleton을 줬습니다.

Close #625

2022-10-25 16:00 UTC, KangYunHo1221 requested changes
고생하셨습니다. 디자인 이쁘네요!

근데 이 PR에 storybook 설치, 버튼 spinner, 디렉토리 변경의 일부까지 세가지가 한번에 들어간 것 같은데 맞나요?

코멘트 남겼으니 확인해주시면 감사하겠습니다 :)

2022-10-25 16:00 UTC, KangYunHo1221 commented on frontend/src/components/@shared/Button/Button.tsx
> +export interface ButtonProps extends React.ComponentPropsWithoutRef<'button'> {
해당 타입을 extends 한 이유는 무엇인가요?

2022-10-25 16:00 UTC, KangYunHo1221 commented on frontend/src/components/@shared/Button/Button.tsx
> +      )}
👍

2022-10-25 16:00 UTC, KangYunHo1221 commented on frontend/src/pages/Hearts/components/ListViewHeart.tsx
> +          isLoading={isLoading}
다른 컴포넌트에서는 Suspense를 사용했는데 여기서는 isLoading을 이용한 이유가

List Item 자체가 통신을 하고 있어서 버튼에는 Suspense를 적용하기 애매한 구조라서 그런것 같은데 맞나요?

Suspense옵션이 켜져있을 때 Suspense와 isLoading가 어떤 순서로 작동할지 궁금하긴 하네요

2022-10-25 16:00 UTC, KangYunHo1221 commented on frontend/src/pages/Hearts/components/ListViewHeartSkeleton.tsx
>    );
Skeleton에 Spinner를 띄운 Button까지 넣으면 어떨지 고민을 해봤습니다.

API별로 Suspense 모습을 구분해 줄 수 없어서

List Item을 조회하는 API와 콕 찌르기 Post요청시에 다른 형태를 보여주는게 맞는 것 같네요.

하나로 전체를 대응하려고 하는 것보다 이대로 가는 것도 좋을 것 같습니다!

2022-10-26 01:16 UTC, kwannee commented on frontend/src/components/@shared/Button/Button.tsx
> +export interface ButtonProps extends React.ComponentPropsWithoutRef<'button'> {
이 타입은 button이 가지고 있는 native 속성들, onClick이나 disabled 같은 속성들도 사용할 수 있게 해줍니다. 
기존에는 `Button` styled-components를 바로 export 해서 거기에 직접 props를 줄 수 있었는데 Spinner를 사용하게 되면서 쌩 styled-component로는 못하게 됐고, 그래서 button의 속성을 그대로 받아올 수 있도록 하기 위해 ComponentPropsWithoutRef<'button'>를 extends 했습니다

2022-10-26 01:18 UTC, kwannee commented on frontend/src/pages/Hearts/components/ListViewHeart.tsx
> +          isLoading={isLoading}
여기서의 isLoading은 mutate에 대한 loading이고 Suspense는 query에 대한 loading이라 서로 다르게 작동할 것 같아요. 그래서 useQuery에만 suspense 옵션이 있는 것 같습니다. 헷갈릴 수 있으니까 isLoading을 다른 이름으로 수정하도록 하겠습니다!

2022-10-26 01:18 UTC, KangYunHo1221 commented on frontend/src/pages/Hearts/components/ListViewHeart.tsx
> +          isLoading={isLoading}
아 맞네요 mutation 이었군요. 감사합니다

2022-10-26 01:32 UTC, KangYunHo1221 commented on frontend/src/components/@shared/Button/Button.tsx
> +export interface ButtonProps extends React.ComponentPropsWithoutRef<'button'> {
```
type ComponentProps<T extends keyof JSX.IntrinsicElements | JSXElementConstructor<any>>
type ComponentPropsWithoutRef = PropsWithoutRef<ComponentProps<T>>;
type PropsWithoutRef<P> = P extends any ? ('ref' extends keyof P ? Pick<P, Exclude<keyof P, 'ref'>> : P) : P;
```

2022-10-26 01:34 UTC, KangYunHo1221 commented on frontend/src/components/@shared/Button/Button.tsx
> +export interface ButtonProps extends React.ComponentPropsWithoutRef<'button'> {
forwardRef의 경우는 ref와 다르게 props가 아닌 다른 인자로 내려주기 때문에
ref를 내려받지 않는다면 componentPropsWithoutRef 가 맞을 것 같네요.

2022-10-26 01:37 UTC, KangYunHo1221 approved these changes
고생하셨씁니다~

2022-10-26 01:45 UTC, merged