refactor: 다양한 접근에 대한 redirect를 처리하는 과정의 가독성을 높인다.
woowacourse-teams/2022-thankoo pull request #629
Opened 2022-10-26 05:40 UTC by kwannee

## 상세 내용
- 역할이 모호했던 컴포넌트와 변수명을 명시적으로 수정했습니다.
  - OrganizationAccess => OrganizationRedirector
  - AccessController => OrganizationInjector
  - axios.ts의 interceptRequest => injectOrganizationToRequest
  - AuthOnly, UnAuthOnly => AuthChecker 라는 파일로 분리
- 유저의 조직을 조회하여 리다이렉트 하는 로직을 명시적으로 리팩터링했습니다.
  - 기존 useGetOrganizations의 return data에 초기값을 줘서 undefined를 제거했습니다.
  - 그 후 isLoading으로 값을 받을 때 까지 기다리던 부분을 Suspense를 사용하도록 변경했습니다.
  - 최근 접속 조직 명을 organization => lastAccessedOrganization으로 수정했습니다.
- page들이 lazy로 code-splitting을 했기 때문에 Suspense를 wrapping 하기 위해 사용됐던 SpinnerSuspense의 이름을 SuspenseWrapper 라는 이름으로 변경했습니다. 
- 

Close #628

2022-10-26 05:57 UTC, kwannee commented on frontend/src/apis/axios.ts
> +export const injectOrganizationToRequest = organizationId => {
정확하게는 organization을 주입하는건데 interceptRequest라는 이름으로 너무 모호했던 것 같습니다. 
또한 intercept 한다는 동작보다는 organization을 inject 한다는게 더 중요한 정보 인것 같다는 점도 변경의 이유였습니다
AxiosRequest 인 것을 명시해줄까 고민해봤는데 axios인지 아는 것은 중요하지 않은 것 같아서 그냥 Request라고만 해줬습니다.

2022-10-26 05:57 UTC, kwannee commented on frontend/src/hooks/@queries/coupon.ts
> +  return { couponDetail: data ?? ({} as CouponDetail), ...rest };
기존 undefined가 나와서 따로 처리해줘야 하던 부분을 초기값을 주는 방식으로 막아봤습니다.
그런데 만약 실제로 서버에서 이상한 값을 던져주면 깨질 수도 있기 때문에 ErrorBoundary를 잘 걸어주는게 중요할 것 같습니다.

2022-10-26 05:57 UTC, kwannee commented on frontend/src/pages/CreateReservation/CreateReservation.tsx
> +    useCreateReservation();
기존에 couponDetail을 넘겼는데 확인해보니 couponDetail에서 receiver를 뽑아내서 사용하고 있었습니다. 
그냥 사용하는 곳에서 바로 사용할 수 있는 형태의 값을 넘기는게 해당 커스텀 훅의 존재 이유인 것 같아서 수정했습니다. 
또한 receiver를 다른 데이터에서 뽑아오도록 변경이 되더라도 사용하는 곳에서는 어쨌든 receiver만 필요한 것이기 때문에 커스텀 훅만 변경하면 컴포넌트에서는 변경하지 않고도 대응이 될 수 있을 것 같습니다.

2022-10-26 05:57 UTC, kwannee commented on frontend/src/routes/AuthChecker.tsx
> +};
기존 route.tsx에 있던 것을 분리 해줬는데요. 이유는 통일성 때문이었습니다. OrganizationInjector나 OrganizationRedirector도 다른 파일로 분리 돼 있어서 얘도 분리 해주는게 통일성 있을 것 같았습니다

2022-10-26 05:57 UTC, kwannee commented on frontend/src/routes/OrganizationInjector.tsx
> +};
컴포넌트를 즉시 실행으로 리턴 후 Suspense로 감싸줬습니다. 컴포넌트 두개 생성안하고 Suspense로 감싸주고 싶어서 이렇게 해봤습니다.
이건 좀 호불호가 갈릴 수도 있을 것 같습니다.

```suggestion
const OrganizationInjector = () => {
  return (
        const { organizations } = useGetOrganizations();

        const lastAccessedOrganization = organizations.find(
          organization => organization.lastAccessed
        );

        if (lastAccessedOrganization) {
          injectOrganizationToRequest(String(lastAccessedOrganization.organizationId));

          return <Outlet />;
        }

        return <Navigate to={ROUTE_PATH.JOIN_ORGANIZATION} />;
      }
};
```
OrganizationInjector를 이렇게만 하고 route.tsx에서 
```jsx
<Route element={<Suspense fallback={<Spinner/>}>
                <OrganizationInjector />
              </Suspense>}/>
```
이런식으로 사용해볼까 했는데 추상화 수준이 안맞아서 혼자 뚱뚱한 느낌이더라고요. 보시고 어떤게 더 읽기 좋은지 얘기 나눠보면 좋을 것 같아요.
개인적으로는 현재 방식은 route를 깔끔하게 유지하는 것 같고, 후자는 OrganizaionInjector의 가독성을 높이는 것 같습니다.

2022-10-26 06:05 UTC, kwannee commented on frontend/src/pages/CreateReservation/CreateReservation.tsx
> +    useCreateReservation();
혹은 ConfirmReservationModalProps라는 이름의 객체를 커스텀 훅에서 리턴해서 해당 객체를 그대로 스프레드하는것도 좋을 것 같습니다. 변경이 생기더라도 커스텀 훅만 바꿔주면 될 것 같아요
```jsx
<ConfirmReservationModal 
  {...ConfirmReservationModalProps}
/>
```

2022-10-27 10:48 UTC, KangYunHo1221 requested changes
리뷰 남겼습니다.

2022-10-27 10:48 UTC, KangYunHo1221 commented on frontend/src/pages/CreateReservation/CreateReservation.tsx
> +    useCreateReservation();
좋네요!

2022-10-27 10:48 UTC, KangYunHo1221 commented on frontend/src/routes/OrganizationInjector.tsx
> +    </Suspense>
화살표함수에 즉시실행 함수 쓰는 구조가 쉽지는 않네요
Suspense가 꼭 필요한 경우일까요?
최상단에서 잡지 않고 여기서 사용한 이유가 무엇인가요?

2022-10-27 10:48 UTC, KangYunHo1221 commented on frontend/src/apis/axios.ts
> +export const injectOrganizationToRequest = organizationId => {
좋습니다 전체적으로 네이밍이 맘에 드네요

2022-10-27 10:48 UTC, KangYunHo1221 commented on frontend/src/hooks/@queries/organization.ts
> +
```suggestion
return {organizations: organizations || [], ...rest};
```

로도 충분하지 않을까요??

아니면 initialValue 적용해줘도 좋을 것 같습니다

2022-10-27 11:08 UTC, kwannee commented on frontend/src/routes/OrganizationInjector.tsx
> +    </Suspense>
suspense가 위로 전파돼어 다른 비동기 통신과 함께 처리되는 일을 걱정했습니다. 그러나 찾아보니 컴포넌트가 다른 경우에는 병렬적으로 비동기 통신을 시작하더라고요. 여기서 suspense를 넣어주지 않더라도 최상단의 SuspenseWrapper가 잡아낼 것 같습니다. 수정완료했습니다!

2022-10-27 11:29 UTC, kwannee commented on frontend/src/hooks/@queries/organization.ts
> +
오우 좋습니다 정상적으로 잘 작동하는군요!

추가적으로 배열의 경우는 undefined 시 이렇게 빈 배열을 내려주도록 하고, 객체의 경우는 그대로 내려주어 사용하는 곳에서 타입 가드를 하는 방식으로 가면 좋을 것 같습니다!
라고 회의 했음

2022-10-27 13:06 UTC, KangYunHo1221 commented on frontend/src/hooks/@queries/organization.ts
> +
좋은 것 같다고 한 것 같은 기억이 나네요 좋습니다.

2022-10-27 13:06 UTC, KangYunHo1221 approved these changes

2022-11-07 05:04 UTC, merged