fix: ChoiceSlider의 option을 2개 이상 사용할 때 UI가 깨지는 문제를 해결한다.
woowacourse-teams/2022-thankoo pull request #639
Opened 2022-11-01 07:26 UTC by kwannee

## 상세 내용
- ChoiceSlider의 z-index를 주는 로직을 수정했습니다.
  - 총 option의 개수 - 해당 index 로 z-index를 줍니다.
  - 기존 사용하는 곳에서 필수적으로 주던 index를 ChoiceSlider 안에서 주도록 숨깁니다.
  - 불필요한 Inner wrapper가 있어서 삭제했습니다.
  - 기존 Content라는 이름을 Toggle로 수정했습니다. UI 컴포넌트 사이트들을 보니 Toggle이란 이름을 많이 쓰는 것을 확인했습니다.
  - 컴포넌트 props에 어느 정도 타입을 줬습니다.
 
 ## 완료하지 못한 내용
- 정확한 타이핑을 하지 못했습니다.
- 가령 Options의 자식으로는 OptionItem이 와야한다. 혹은 Options의 자식은 3개 이하여야 한다 등을 타입으로 주고 싶었으나 잘 안됐습니다.

Close #638

2022-11-01 09:50 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> -ChoiceSlider.Inner = ({ children, ...props }) => {
Inner가 불필요하게 사용되고 있어서 제거했습니다.

2022-11-01 09:50 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  }
자식이 3개 초과일 때 에러를 던집니다.
실행 이전에 타입으로 알려주고 싶었는데 잘 안됐습니다. 방법을 아시나요?

2022-11-01 09:50 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  }
또한 Options의 props로 children은 OptionItem이어야만 한다는 것도 주고 싶었는데 잘 안됐습니다.
typeof instanceof OptionItem를 사용했었습니다.

2022-11-01 09:50 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  });
기존에는 index를 사용하는 곳에서 명시해줬는데, 사용하는 곳에서 index 명시하는 건 좀 사용성이 안좋다고 판단했습니다. 그래서 index를 아예 포함하고 있는 children을 새로 만들었습니다. 이렇게 하니까 타입 달기가 좀 애매해지긴 했습니다.

2022-11-01 09:50 UTC, kwannee commented on frontend/src/pages/Reservations/components/ListReservationItem.tsx
> +          </Slider.OptionItem>
수정 후 OptionItem에는 배경색상만 넘기도록 수정했습니다. 색상은 사용처에서 수정하는게 더 사용성이 좋다고 판단했습니다.

2022-11-02 08:38 UTC, KangYunHo1221 requested changes
suggestion을 작성하다가 시간이 오래걸렸네요 죄송합니다.

request change 확인 부탁드립니다.

2022-11-02 08:38 UTC, KangYunHo1221 commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  }
음 해당 타입은 주기 힘들 것 같기도 하네요 일단 그냥 진행해도 될 것 같습니다

2022-11-02 08:38 UTC, KangYunHo1221 commented on frontend/src/pages/Reservations/components/ListReservationItem.tsx
> +      <Slider.Toggle>
ChoiceSlider 컴포넌트인데 Slider로 이름을 지정해서 사용하는 이유가 있나요?

2022-11-02 08:38 UTC, KangYunHo1221 commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  }
이거 ts-checker가 감지를 못하네요... 저도 해봤는데 현재 상태로 해야할 것 같습니다.
컴파운드 컴포넌트이기 때문에 충분히 인지 가능할 것 같습니다.
길이는 제한할 수 있지만 div나 fragment로 감싸면 충분히 숨길 수 있어서 추가하지 않아도 될 것 같습니다

2022-11-02 08:38 UTC, KangYunHo1221 commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  });
```suggestion
//outside of ChoiceSlider.Options
const isMultipleChildren = (input): input is ReactElement[] => {
  return Array.isArray(input);
};

//inside of ChoiceSlider.Options
 let chidrenArr = isMultipleChildren(children) ? children : [children];

  const indexedChildren = chidrenArr.map((child, idx): ReactElement => {
    const reactElementChild = { ...child, props: { index: idx + 1, ...child.props } };
    return reactElementChild;
  });
```
타입단언을 제거해 주는건 어떨까요?

2022-11-02 08:38 UTC, KangYunHo1221 commented on frontend/src/pages/Reservations/components/ListReservationItem.tsx
> +          </Slider.OptionItem>
좋습니다.

2022-11-02 08:41 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  }
5시간동안 고생많으셨습니다...

2022-11-02 08:48 UTC, kwannee commented on frontend/src/pages/Reservations/components/ListReservationItem.tsx
> +      <Slider.Toggle>
ChoiceSlider라는 이름이 너무 길어 변경해서 사용하려는 의도였습니다!

2022-11-02 11:58 UTC, kwannee commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  });
react에서 제공하는 메서드를 사용하고 싶었는데 그러면 ReactElement를 사용할 수가 없군요. 리액트 이 구속적인 녀석들...
수정 완료했습니다

2022-11-02 16:07 UTC, KangYunHo1221 commented on frontend/src/pages/Reservations/components/ListReservationItem.tsx
> +      <Slider.Toggle>
현재는 파악하는데 어려움이 없어서 approve하겠습니다.
사용하는 곳에서 헷갈릴 가능성이 있어서 한군데 이상 더 사용한다면 이름을 통일해야할 것 같아요

2022-11-02 16:08 UTC, KangYunHo1221 commented on frontend/src/components/@shared/ChoiceSlider.tsx
> +  });
왜 generic으로 input따라 안주고 합타입으로 줬는지 잘 모르겠네요.. 까먹었나?
나중에 issue날려서 컨트리뷰터 하고싶네요ㅋㅋㅋ

2022-11-02 16:09 UTC, KangYunHo1221 commented
훨씬 나아졌네요 굿잡 머지하겠습니다.
고생하셨어요

2022-11-02 16:09 UTC, KangYunHo1221 approved these changes
문제파악(쿠폰이 없다면 쓰지 않을 것이다) 트러블슈팅(사용자 수를 늘리자) 해결방안(접근이 쉬운 uiux 제공, 가벼운 컨텐츠, 정렬방식을 통한 사용자 편의, 복수전송 막음)

2022-11-02 16:09 UTC, merged