refactor : Avatar와 ListRow를 구현하고 변경사항을 적용한다.
woowacourse-teams/2022-thankoo pull request #643
Opened 2022-11-08 10:44 UTC by kwannee

## 상세 내용
- Avatar를 구현하고 해당 컴포넌트로 모두 교체했습니다.
  - size를 숫자로 타이핑했습니다. sm, md, lg로 줘봤는데 그냥 숫자로 주는게 더 직관적이고 좋을 것 같았습니다.
  - Icon 귀가 잘려있던거 이제야 발견했습니다. border-radius 삭제해서 귀 붙여줬습니다.
- 토스식 ListRow를 카피캣하고 관련 컴포넌트 중 ListViewUser와 ListViewReservation을 교체했습니다.

2022-11-08 10:55 UTC, kwannee reviewed
리뷰해주세용

2022-11-08 10:55 UTC, kwannee commented on frontend/src/components/ListRow.tsx
> +type Text2RowsElement = ReactElement<ComponentProps<typeof ListRow.Text2Rows>>;
이거 해줘도 안먹더라고요 어쩔 수 없나봐요.

2022-11-08 10:55 UTC, kwannee commented on frontend/src/pages/Profile/components/SelectProfileImgModal.tsx
> +];
원래 constants/profileIcon에 있었습니다.
다른 곳에서 사용하는 것 같지 않고, 관리할 필요가 없을 것 같아서  사용하는 컴포넌트로 이동해줬습니다.

2022-11-08 10:55 UTC, kwannee commented on frontend/src/pages/Profile/components/SelectProfileImgModal.tsx
> +  });
`유저 프로필 이미지`를 변경하는 건 `유저 프로필 선택`의 책임이라 생각해 해당 mutate를 모달 내부로 이동시켰습니다.

2022-11-09 08:41 UTC, KangYunHo1221 requested changes
고생하셨습니다.
코드 깔끔해서 좋네요~

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/types/coupon.ts
> +export type CouponTransmitableType = Exclude<CouponType, 'entire'>;
good!

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/layout/TopNavBar.tsx
> +        <Avatar src={profile?.imageUrl} userName={profile?.name} />
username을 왜 받았었지 했는데 alt값을 주기 위해서 였군요?
필수는 아니고 추후에 접근성 개선에 더 유리하려면 user 자체를 넘겨 받는 방식이 더 나을수도 있겠네요

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/pages/Profile/components/SelectProfileImgModal.tsx
> +];
뺐어야 했는데, 기간이 급해서 만한 슈퍼 레거시였는데 감사합니다.

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +      {...props}
inline css 로 내려준 특별한 이유가 있을까요?

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/pages/SelectReceiver/components/ListViewUsers.tsx
> +            />
어라..? 어디 과제에서 많이 보던 코드스타일이..?

2022-11-09 08:41 UTC, KangYunHo1221 commented on frontend/src/pages/SelectReceiver/components/ListViewUsers.tsx
> +          onClick={() => onClickUser(user)}
요것만 좀 바꿔볼까요?
onClick하면 뭐하는지 잘 모르겠네요.
저희 원래 ```onclick(()=>{onClick()}``` 안썼으니까 바꾸는게 낫겠네요

2022-11-09 14:06 UTC, kwannee commented on frontend/src/layout/TopNavBar.tsx
> +        <Avatar src={profile?.imageUrl} userName={profile?.name} />
오우 userName이라는 props가 은근히 범용성이 떨어지더라고요. 나중에는 그냥 alt라는 이름으로 변경했습니다. alt는 강제로 주도록 해서 접근성도 챙겨봤어요.

2022-11-09 14:07 UTC, kwannee commented on frontend/src/components/ListRow.tsx
> +      {...props}
그것이... emotion의 사용 이유니깐... (토스가 그렇게 하길래)

2022-11-09 14:07 UTC, kwannee commented on frontend/src/pages/SelectReceiver/components/ListViewUsers.tsx
> +            />
착각입니다~~

2022-11-09 14:07 UTC, kwannee commented on frontend/src/pages/SelectReceiver/components/ListViewUsers.tsx
> +          onClick={() => onClickUser(user)}
오 맞아 까먹고 있었네요 수정하겠습니다

2022-11-09 14:08 UTC, kwannee commented on frontend/src/pages/Profile/components/SelectProfileImgModal.tsx
> +];
아 돼지가 아니라 후니로 바꿨어야 했는데 까먹었네요 수정하겠습니다~

2022-11-10 01:59 UTC, kwannee reviewed
수정했습니다~~

2022-11-10 01:59 UTC, kwannee commented on frontend/src/components/ListRow.tsx
> -} & ComponentPropsWithoutRef<'div'>;
이거있으니까 div의 모든 props들이 다 떠서 left,center,right 등 실제로 사용하는 prop들이 추천 목록에 안뜨더라고요 그래서 뺐습니다.

2022-11-10 01:59 UTC, kwannee commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
하나 대박인거 알아냈습니다. 이 컴포넌트에 default css가 있잖아요? display : grid 주고 하는거. 

그거에 추가로 css를 props로 받으려고 css라는 props를 뚫었는데 css props는 2개 연속 사용이 안되더라고요?
어떻게 하는건지 찾아봤는데 css prop은 css라는 이름으로 받는게 아니라 className으로 받는거 였어요.
t모 기업도 className을 이 컴포넌트에서 받길래 왜 받는걸까 싶었는데 커스텀 css props를 받으려고 그런거 였습니다. 역시 다 이유가 있었어요.

2022-11-10 01:59 UTC, kwannee commented on frontend/src/pages/SelectReceiver/components/ListViewUsers.tsx
> +  onClickUser: toggleCheckedUser,
onClickUser는 사용하는 곳에서는 onClick으로 시작하는게 맞기 때문에 유지했습니다.
대신 ListViewUsers에서는 toggleCheckedUser로 역할을 분명히 명시해줬습니다.

2022-11-10 01:59 UTC, kwannee commented on frontend/src/pages/SelectReceiver/components/CheckedUsers.tsx
> +    height: ${({ hasCheckedUser }) => (hasCheckedUser ? '6rem' : 0)};
이렇게 length 없을 때는 height 0 줬다가 length 있으면 height 주는 식으로 애니메이션을 줬습니다.

https://user-images.githubusercontent.com/41886825/200981804-414b38f5-cb05-4f75-be63-c29a789ac1ed.mov

2022-11-10 11:30 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
오 신통방통하네요?

근데 listRow의 
```javascript
css={{
        display: 'grid',
        gridTemplateColumns: '1fr 3fr 1fr',
      }}
```
를 styled component로 만들어주고 className 대신 css를 전달받지 않는 이유가 있나요?

2022-11-10 11:30 UTC, KangYunHo1221 commented on frontend/src/pages/Profile/components/SelectProfileImgModal.tsx
> +];
하는김에 스꺼리도 똥커리로 바꾸죠

2022-11-10 11:30 UTC, KangYunHo1221 commented on frontend/src/layout/TopNavBar.tsx
> +        <Avatar src={profile?.imageUrl} userName={profile?.name} />
alt로 받는게 낫네요 굳굳

2022-11-10 11:30 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +      {...props}
음.. 쓰면서 아직 저게 사용하기 좋은 이유는 못찿긴 했습니다 ㅋㅋ

2022-11-10 11:32 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
오 신통방통하네요... 근데
```javascript
css={{
        display: 'grid',
        gridTemplateColumns: '1fr 3fr 1fr',
      }}
```
를 Styled Component로 분리한 다음 css를 prop으로 받지 않고 이런 방식을 사용하는 이유가 있나요?

2022-11-10 11:38 UTC, KangYunHo1221 commented on frontend/src/pages/SelectReceiver/components/CheckedUsers.tsx
> +    height: ${({ hasCheckedUser }) => (hasCheckedUser ? '6rem' : 0)};
굳굳

2022-11-10 12:15 UTC, kwannee commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
일단 가장 큰 이유는 styled-component로 하면 동작이 안됩니다. 그 이유는 css-in-js가 className으로 동작하기 때문입니다. 
css-in-js는 className을 할당하고 그 className에 맞는 스타일을 생성하는 방식으로 동작합니다. 
styled-component를 만들면 1차로 className이 설정되는데, 거기에 추가로 className을 줘버리면 기존 className을 덮어 씌우는 형식이라 styled-component의 style이 오버로드 돼버립니다. 이건 css를 prop으로 받아도 마찬가지입니다. css도 className을 만드는 방식이라 여전히 기존 className을 오버로드해 스타일을 덮어씌워버립니다.

디폴트 스타일이 css inline이고 사용하는 곳에서 className으로 커스텀 스타일을 주면 두 className이 합쳐져서 새로운 className이 됩니다. 물론 두 스타일 모두가 적용되고요. 그래서 이런 방법으로 두 css props를 합쳐서 사용할 수 있습니다.

두번째 이유는 코드가 깔끔해져서 입니다.
기존 도메인 관련 컴포넌트들은 styled-component를 통해서 의미론적으로 이름을 지어줬는데 얘는 도메인 로직이 없는 컴포넌트입니다. 그래서 지어줄 이름이 마땅치 않았습니다. Container 정도가 떠오르는데 이거는 너무 무의미한 이름이라서 이럴거면 굳이 styled-component로 만들지 않아도 되겠다는 판단을 했습니다.
또한 이 컴포넌트는 도메인 관련 일반 컴포넌트 처럼 꾸준히 들어가서 확인하는 컴포넌트가 아닙니다. 사용법만 알면 굳이 이 컴포넌트를 보러 들어올 필요가 없을 것 같았습니다. 따라서 import도 줄이고 styled-component 선언하는 코드도 줄이는 방향으로 가는게 낫겠다는 판단을 했습니다.

2022-11-10 16:35 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
styled component 내에 css object 형식으로 할당이 가능하긴 합니다.
사실 styled component만 이용해도 emotion과 똑같이 구현은 가능할겁니다.(styled component가 몇개 더 늘긴 하겠지만요)

다만 말씀하신 것처럼 css prop 형태가 emotion에서 추천하는 방식이기 때문에 이렇게 가는게 좋겠네요.
익숙해지면 좀 더 이해하기에 깔끔한 코드가 맞는 것 같습니다.

2022-11-10 16:35 UTC, KangYunHo1221 approved these changes
고생하셨습니다. css props가 emotion에서 추천하는 방식이라는 거 하나 배워갑니다!!
머지할게요

2022-11-10 16:36 UTC, merged

2022-11-10 16:38 UTC, KangYunHo1221 commented on frontend/src/components/ListRow.tsx
> +  onClick?: () => void;
inline으로 컴포넌트에 object 를 props로 내려주면 불변성을 지키려고 계속 새로운 오브젝트를 생성할텐데, 이 측면에서는 메모리가 어떻게 될지 궁금하긴 하네요.
styled component는 컴포넌트라서 리액트가 관리해 줄 것 같긴 합니다.